### PR TITLE
Us631688: Add analytics schema name

### PR DESCRIPTION
**Pull request by APIM-KiranVaddadi**
## Description
Adding DB schema name env variable with value portal_analytics.

## Links
Link Type   | Link
------      | ------
Rally Story| Us631688
Func Spec   | 

## Checklist
- [x] Pull Request Created
- [ ] Code Review Completed
- [ ] Integration/Functional test cases have been written and automated
- [x] Func Spec has been updated as needed
- [ ] Rally Issue(s) are in an engineering completed state

### CODE REVIEW

**Comment by ken-chou** [comment]
What is the slated release for these changes?

**Comment by APIM-KiranVaddadi** [comment]
> What is the slated release for these changes?

4.5

**Comment by ken-chou** [comment]
Can you please create a PR to branch "release-4.5" then. This is to keep master available for 4.4 fixes.

**Comment by ken-chou** [comment]
Closed in favour of https://github.com/CAAPIM/portal-helm-charts/pull/16/files

**Pull request closed without merging**
